"""OAuth 2.1 production access boundary built from MCP/FastMCP SDK primitives.

No OAuth protocol code is hand-written here. The protocol surface comes from the
SDK: ``mcp.server.auth.routes.create_auth_routes`` serves RFC 8414 discovery,
``/authorize`` (request validation + redirect) and ``/token`` (client
authentication, PKCE S256 verification, redirect binding); dynamic client
registration is ``/register``; ``fastmcp.server.auth.cimd.CIMDClientManager``
resolves ChatGPT-style URL client identities (CIMD); redirect URIs are checked
with ``fastmcp.server.auth.redirect_validation.validate_redirect_uri`` against
the CIMD document's allowlist; tokens are minted with
``fastmcp.server.auth.jwt_issuer.JWTIssuer`` (iss/aud/sub/scope/iat/exp/jti) and
verified by ``fastmcp.server.auth.providers.jwt.JWTVerifier``; RFC 9728
protected-resource metadata is generated by
``fastmcp.server.auth.RemoteAuthProvider``.

This module only supplies the YY-specific glue: the authorization provider hooks
(owner login + single-use code store), the RFC 8707 ``resource`` binding across
the authorize/exchange chain, the anonymous-allowed / invalid-bearer-fail-closed
ASGI policy, per-request caller-scope resolution, and credential hardening
(PBKDF2-HMAC-SHA256 + constant-time compare + per-IP login throttling).
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import html
import json
import secrets
import time
import urllib.parse
from typing import Any

from fastmcp.server.auth import RemoteAuthProvider
from fastmcp.server.auth.cimd import CIMDClientManager, CIMDDocument
from fastmcp.server.auth.jwt_issuer import JWTIssuer, derive_jwt_key
from fastmcp.server.auth.providers.jwt import JWTVerifier
from fastmcp.server.auth.redirect_validation import validate_redirect_uri
from mcp.server.auth.provider import (
    AccessToken,
    AuthorizationCode,
    AuthorizationParams,
    OAuthAuthorizationServerProvider,
    OAuthToken,
    construct_redirect_uri,
)
from mcp.server.auth.routes import create_auth_routes
from mcp.server.auth.settings import ClientRegistrationOptions
from mcp.shared.auth import OAuthClientInformationFull
from pydantic import AnyHttpUrl, AnyUrl, ValidationError
from starlette.middleware import Middleware
from starlette.requests import Request
from starlette.responses import HTMLResponse, JSONResponse, RedirectResponse
from starlette.routing import BaseRoute, Route

SCOPE_LEVELS = {"synthetic": 0, "production": 1}
PRODUCTION_SCOPE = "production"
SYNTHETIC_SCOPE = "synthetic"
SUPPORTED_SCOPES = (PRODUCTION_SCOPE, SYNTHETIC_SCOPE)
ACCESS_TOKEN_TTL_SECONDS = 3600
AUTHORIZATION_CODE_TTL_SECONDS = 300
REQUIRED_SECRET_CHARS = 32
PBKDF2_ITERATIONS = 600_000
PASSWORD_HASH_PREFIX = "pbkdf2_sha256"
THROTTLE_THRESHOLD = 3
THROTTLE_DELAY_SECONDS = 5.0
LOGIN_PATH = "/login"
TOKEN_PATH = "/token"
MCP_RESOURCE_PATHS = ("/mcp", "/mcp-v2")
WELL_KNOWN_PROTECTED_RESOURCE = "/.well-known/oauth-protected-resource"
CLAIMS_SCOPE_KEY = "yy_auth_claims"
OWNER_SUBJECT = "yy-owner"
LOGIN_FORM_FIELDS = (
    "response_type", "client_id", "redirect_uri", "state",
    "code_challenge", "code_challenge_method", "scope", "resource",
)

_auth_secret: str | None = None
_auth_password_hash: str | None = None
_auth_issuer: str | None = None


class LoginThrottler:
    """Per-client-IP bounded failure delay; process-level, not a full IAM."""

    def __init__(
        self,
        threshold: int = THROTTLE_THRESHOLD,
        delay: float = THROTTLE_DELAY_SECONDS,
        clock: Any = time.time,
        max_entries: int = 4096,
    ) -> None:
        self._threshold = threshold
        self._delay = delay
        self._clock = clock
        self._max_entries = max_entries
        self._failures: dict[str, int] = {}
        self._blocked_until: dict[str, float] = {}

    def retry_after(self, client_ip: str) -> float:
        """Seconds the client must still wait; 0 means the attempt is allowed."""
        blocked = self._blocked_until.get(client_ip, 0.0)
        return max(0.0, blocked - self._clock())

    def record_failure(self, client_ip: str) -> None:
        count = self._failures.get(client_ip, 0) + 1
        self._failures[client_ip] = count
        if count >= self._threshold:
            self._blocked_until[client_ip] = self._clock() + self._delay
        while len(self._failures) > self._max_entries:
            self._failures.pop(next(iter(self._failures)))

    def record_success(self, client_ip: str) -> None:
        self._failures.pop(client_ip, None)
        self._blocked_until.pop(client_ip, None)

    def reset(self) -> None:
        self._failures.clear()
        self._blocked_until.clear()


_throttler = LoginThrottler()


def configure_auth(secret: str | None, password_hash: str | None, issuer: str | None = None) -> None:
    """Install the signing secret, PBKDF2 password hash, and public issuer."""
    global _auth_secret, _auth_password_hash, _auth_issuer
    if not secret or len(secret) < REQUIRED_SECRET_CHARS:
        raise ValueError("YY_AUTH_SECRET must be at least 32 characters.")
    if _parse_password_hash(password_hash or "") is None:
        raise ValueError(
            "YY_AUTH_PASSWORD_HASH must be a pbkdf2_sha256 encoding from auth.hash_password()."
        )
    _auth_secret = secret
    _auth_password_hash = password_hash
    _auth_issuer = (issuer or "").rstrip("/") or None
    _throttler.reset()


def reset_auth() -> None:
    """Clear configuration and in-flight codes (test isolation only)."""
    global _auth_secret, _auth_password_hash, _auth_issuer
    _auth_secret = None
    _auth_password_hash = None
    _auth_issuer = None
    _throttler.reset()


def normalize_scope(value: Any) -> str:
    """Map any scope value onto the two-level lattice; unknown means synthetic."""
    scopes = value.split() if isinstance(value, str) else []
    return PRODUCTION_SCOPE if PRODUCTION_SCOPE in scopes and all(
        scope in SUPPORTED_SCOPES for scope in scopes
    ) else SYNTHETIC_SCOPE


# --- Credential hardening (PBKDF2-HMAC-SHA256) ---
def hash_password(password: str, *, iterations: int = PBKDF2_ITERATIONS, salt: bytes | None = None) -> str:
    """Encode a password as pbkdf2_sha256$<iters>$<salt>$<digest> (base64)."""
    if iterations < 1:
        raise ValueError("iterations must be positive")
    salt = salt or secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, iterations)
    return "$".join((
        PASSWORD_HASH_PREFIX,
        str(iterations),
        base64.b64encode(salt).decode("ascii"),
        base64.b64encode(digest).decode("ascii"),
    ))


def _parse_password_hash(encoded: str) -> tuple[bytes, int, bytes] | None:
    """Return (salt, iterations, expected_digest) for a stored hash; else None."""
    parts = (encoded or "").strip().split("$")
    if len(parts) != 4 or parts[0] != PASSWORD_HASH_PREFIX:
        return None
    try:
        iterations = int(parts[1])
        salt = base64.b64decode(parts[2], validate=True)
        digest = base64.b64decode(parts[3], validate=True)
    except (ValueError, TypeError):
        return None
    if iterations < 1 or not salt or not digest:
        return None
    return salt, iterations, digest


def verify_password(password: str) -> bool:
    """Constant-time PBKDF2 verification against the configured hash."""
    parsed = _parse_password_hash(_auth_password_hash or "")
    if parsed is None:
        return False
    salt, iterations, expected = parsed
    actual = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, iterations)
    return hmac.compare_digest(actual, expected)


def _client_ip(request: Request) -> str:
    return request.client.host if request.client else "unknown"


# --- Caller scope resolution (request-scoped only; no shared global state) ---
def current_caller_scope() -> str:
    """Scope of the current MCP request; synthetic unless its token says otherwise.

    Claims come exclusively from the current ASGI/MCP request context, so
    concurrent requests can never observe each other's authorization.
    """
    try:
        from fastmcp.server.dependencies import get_http_request
        claims = get_http_request().scope.get(CLAIMS_SCOPE_KEY)
    except Exception:
        claims = None
    if isinstance(claims, dict):
        return normalize_scope(claims.get("scope"))
    return SYNTHETIC_SCOPE


def _bearer_token_from_scope(scope: dict) -> tuple[bool, str | None]:
    """Return (header_present, bearer_token_or_None) from raw ASGI headers."""
    for name, value in scope.get("headers") or []:
        if name.lower() != b"authorization":
            continue
        scheme, _, token = value.decode("latin-1").strip().partition(" ")
        if scheme.lower() != "bearer":
            return True, None
        return True, token.strip() or None
    return False, None


class BearerChallengeMiddleware:
    """Anonymous-allowed, invalid-bearer fail-closed ASGI middleware (RFC 6750).

    On MCP resource paths, a missing Authorization header means anonymous
    synthetic access. Any present header must carry a token that verifies (signature, issuer,
    audience, expiry, supported scopes); otherwise the request is rejected with
    401 and a ``WWW-Authenticate`` challenge pointing at the RFC 9728 metadata.
    Authorization server routes keep the SDK's client authentication policy.
    """

    def __init__(self, app: Any, verifier: Any, resource_metadata_url: str) -> None:
        self.app = app
        self.verifier = verifier
        self.resource_metadata_url = resource_metadata_url

    async def __call__(self, scope: dict, receive: Any, send: Any) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return
        path = scope.get("path", "")
        if not any(path == resource or path.startswith(resource + "/") for resource in MCP_RESOURCE_PATHS):
            await self.app(scope, receive, send)
            return
        header_present, token = _bearer_token_from_scope(scope)
        if not header_present:
            scope[CLAIMS_SCOPE_KEY] = None
            await self.app(scope, receive, send)
            return
        if token is None:
            await self._reject(send, "invalid_request", "Bearer authentication is required.")
            return
        access_token = await self.verifier.verify_token(token)
        if access_token is None or not self._scopes_supported(access_token):
            await self._reject(send, "invalid_token", "Access token is invalid, expired, or has unknown scopes.")
            return
        claims = dict(access_token.claims or {})
        claims["scope"] = " ".join(access_token.scopes)
        scope[CLAIMS_SCOPE_KEY] = claims
        await self.app(scope, receive, send)

    @staticmethod
    def _scopes_supported(access_token: AccessToken) -> bool:
        scopes = access_token.scopes or []
        return bool(scopes) and all(scope in SUPPORTED_SCOPES for scope in scopes)

    async def _reject(self, send: Any, error: str, description: str) -> None:
        www_authenticate = ", ".join((
            f"Bearer error=\"{error}\"",
            f"error_description=\"{description}\"",
            f"resource_metadata=\"{self.resource_metadata_url}\"",
        ))
        body = json.dumps({"error": error, "error_description": description}).encode("utf-8")
        await send({
            "type": "http.response.start",
            "status": 401,
            "headers": [
                (b"content-type", b"application/json"),
                (b"content-length", str(len(body)).encode("ascii")),
                (b"www-authenticate", www_authenticate.encode("utf-8")),
            ],
        })
        await send({"type": "http.response.body", "body": body})


# --- Authorization server provider (SDK protocol hooks) ---
class YYTokenVerifier(JWTVerifier):
    """HS256 JWT verifier bound to the YY issuer and canonical resource audience.

    ``verify_token`` (inherited) checks signature, ``iss``, ``aud == canonical
    YY MCP resource``, ``exp``, and scopes, returning an ``AccessToken`` or
    ``None``; ``None`` makes the bearer middleware fail closed with 401.
    """

    def __init__(self, *, signing_key: bytes, issuer: str, resource: str) -> None:
        super().__init__(public_key=signing_key, algorithm="HS256", issuer=issuer, audience=resource)


class YYAuthorizationServerProvider(OAuthAuthorizationServerProvider):
    """YY authorization hooks over the SDK protocol; CIMD-resolved clients.

    The SDK handlers own request validation, PKCE, redirect binding at /token,
    and client authentication. This provider owns the owner login, the
    single-use authorization-code store (with the RFC 8707 ``resource``
    binding), and JWT minting for ``exchange_authorization_code``.
    """

    def __init__(
        self,
        client_manager: CIMDClientManager,
        token_issuer: JWTIssuer,
        verifier: YYTokenVerifier,
        resource: str,
    ) -> None:
        self.client_manager = client_manager
        self.token_issuer = token_issuer
        self.verifier = verifier
        self.resource = resource
        self._clients: dict[str, OAuthClientInformationFull] = {}
        self._authorization_codes: dict[str, AuthorizationCode] = {}

    # -- client resolution: process registry first, then CIMD discovery --
    async def get_client(self, client_id: str) -> OAuthClientInformationFull | None:
        key = str(client_id).rstrip("/")
        client = self._clients.get(key)
        if client is not None:
            return client
        if self.client_manager.is_cimd_client_id(str(client_id)):
            client = await self.client_manager.get_client(str(client_id))
            if client is not None:
                self._clients[key] = client
            return client
        return None

    async def register_client(self, client_info: OAuthClientInformationFull) -> None:
        """Dynamic registration (RFC 7591): persist the SDK-issued client."""
        self._clients[str(client_info.client_id).rstrip("/")] = client_info

    def seed_cimd_document(self, document: CIMDDocument) -> str:
        """Register a CIMD document without network fetch (deploy seeds/tests).

        Builds exactly the synthetic client ``CIMDClientManager.get_client``
        builds after a successful document fetch.
        """
        from fastmcp.server.auth.oauth_proxy.models import ProxyDCRClient

        client = ProxyDCRClient(
            client_id=str(document.client_id),
            client_secret=None,
            redirect_uris=None,
            grant_types=document.grant_types,
            scope=document.scope or self.client_manager.default_scope,
            token_endpoint_auth_method=document.token_endpoint_auth_method,
            allowed_redirect_uri_patterns=self.client_manager.allowed_redirect_uri_patterns,
            client_name=document.client_name,
            cimd_document=document,
            cimd_fetched_at=time.time(),
        )
        self._clients[str(document.client_id).rstrip("/")] = client
        return str(document.client_id)

    # -- authorization endpoint hook: hand off to the owner login form --
    async def authorize(self, client: OAuthClientInformationFull, params: AuthorizationParams) -> str:
        query = urllib.parse.urlencode({
            "response_type": "code",
            "client_id": str(client.client_id),
            "redirect_uri": str(params.redirect_uri),
            "state": params.state or "",
            "code_challenge": params.code_challenge,
            "code_challenge_method": "S256",
            "scope": " ".join(params.scopes or []) ,
            "resource": params.resource or "",
        })
        return f"{LOGIN_PATH}?{query}"

    # -- single-use code store with resource binding --
    def issue_authorization_code(
        self,
        client: OAuthClientInformationFull,
        redirect_uri: AnyUrl,
        code_challenge: str,
        scopes: list[str],
        resource: str | None,
    ) -> AuthorizationCode:
        self._purge_expired_codes()
        code = AuthorizationCode(
            code=secrets.token_urlsafe(32),
            scopes=scopes,
            expires_at=time.time() + AUTHORIZATION_CODE_TTL_SECONDS,
            client_id=str(client.client_id),
            code_challenge=code_challenge,
            redirect_uri=redirect_uri,
            redirect_uri_provided_explicitly=True,
            resource=resource,
            subject=OWNER_SUBJECT,
        )
        self._authorization_codes[code.code] = code
        return code

    async def load_authorization_code(
        self, client: OAuthClientInformationFull, authorization_code: str
    ) -> AuthorizationCode | None:
        record = self._authorization_codes.pop(str(authorization_code), None)  # single use
        if record is None or record.expires_at < time.time():
            return None
        return record

    async def exchange_authorization_code(
        self, client: OAuthClientInformationFull, authorization_code: AuthorizationCode
    ) -> OAuthToken:
        scopes = list(authorization_code.scopes or [PRODUCTION_SCOPE])
        token = self.token_issuer.issue_access_token(
            client_id=str(client.client_id),
            scopes=scopes,
            jti=secrets.token_hex(16),
            expires_in=ACCESS_TOKEN_TTL_SECONDS,
            subject=authorization_code.subject or OWNER_SUBJECT,
        )
        return OAuthToken(
            access_token=token,
            token_type="Bearer",
            expires_in=ACCESS_TOKEN_TTL_SECONDS,
            scope=" ".join(scopes),
        )

    async def load_access_token(self, token: str) -> AccessToken | None:
        """Resource-server side of the same provider: JWT verification."""
        return await self.verifier.verify_token(token)

    def _purge_expired_codes(self) -> None:
        now = time.time()
        for key in [key for key, code in self._authorization_codes.items() if code.expires_at <= now]:
            del self._authorization_codes[key]

    def token_request_resource_matches(self, code: str, resource: str | None) -> bool:
        """RFC 8707: the /token resource must equal the authorization-time one."""
        record = self._authorization_codes.get(str(code))
        if record is None:
            return True  # unknown codes are rejected by the SDK token handler
        return _normalize_resource(record.resource, self.resource) == _normalize_resource(resource, self.resource)


def _normalize_resource(value: str | None, canonical: str) -> str:
    return (value or canonical).strip().rstrip("/") or canonical.rstrip("/")


# --- Owner login endpoints (the only YY-specific HTTP surface) ---
_LOGIN_PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>YY Web MCP sign-in</title></head>
<body style="font-family:sans-serif;max-width:24rem;margin:4rem auto"><h2>YY Web MCP</h2>
<p>Owner sign-in is required to unlock production workflow bindings.</p>{error}
<form method="post" action="/login">{hidden}
<label>Password <input type="password" name="password" autofocus required></label>
<button type="submit">Sign in</button></form></body></html>"""


def render_login_form(params: dict[str, str], error: str | None = None) -> str:
    hidden = "".join(
        f'<input type="hidden" name="{html.escape(name)}" value="{html.escape(params.get(name, ""))}">'
        for name in LOGIN_FORM_FIELDS
    )
    banner = f'<p style="color:#b00020">{html.escape(error)}</p>' if error else ""
    return _LOGIN_PAGE.format(error=banner, hidden=hidden)


def _redirect_patterns(client: OAuthClientInformationFull) -> list[str]:
    """Exact allowlist: CIMD document redirect_uris, else registered ones."""
    document = getattr(client, "cimd_document", None)
    source = document.redirect_uris if document is not None and document.redirect_uris else client.redirect_uris
    return [str(uri) for uri in (source or [])]


class LoginRequestError(Exception):
    def __init__(self, error: str, description: str) -> None:
        super().__init__(description)
        self.error = error
        self.description = description


async def validate_login_request(provider: YYAuthorizationServerProvider, params: dict[str, str]):
    """Re-validate the preserved authorization request behind the login form."""
    if params.get("response_type") != "code":
        raise LoginRequestError("unsupported_response_type", "response_type must be 'code'.")
    if params.get("code_challenge_method") != "S256":
        raise LoginRequestError("invalid_request", "code_challenge_method must be S256.")
    challenge = params.get("code_challenge", "")
    if not 43 <= len(challenge) <= 128:
        raise LoginRequestError("invalid_request", "code_challenge must be 43-128 characters.")
    client = await provider.get_client(params.get("client_id", ""))
    if client is None:
        raise LoginRequestError("invalid_request", f"Client ID '{params.get('client_id', '')}' not found.")
    try:
        redirect_uri = AnyUrl(params.get("redirect_uri", ""))
    except ValidationError as validation_error:
        raise LoginRequestError("invalid_request", "redirect_uri is not a valid URI.") from validation_error
    if not validate_redirect_uri(str(redirect_uri), _redirect_patterns(client)):
        raise LoginRequestError(
            "invalid_request",
            f"Redirect URI '{redirect_uri}' is not on the client allowlist.",
        )
    requested = (params.get("scope") or "").split()
    granted = [scope for scope in requested if scope in SUPPORTED_SCOPES]
    if requested and len(granted) != len(requested):
        raise LoginRequestError("invalid_scope", "Requested scope is not supported.")
    if not granted:
        granted = [PRODUCTION_SCOPE]  # single-owner server: login grants production
    resource = params.get("resource") or None
    if resource is not None and _normalize_resource(resource, provider.resource) != _normalize_resource(None, provider.resource):
        raise LoginRequestError("invalid_target", "resource must be this MCP server.")
    return client, redirect_uri, challenge, granted, resource


def build_login_routes(provider: YYAuthorizationServerProvider) -> list[BaseRoute]:
    """Owner password login preserving the validated authorization request."""

    async def login_endpoint(request: Request) -> Any:
        if request.method == "GET":
            params = {name: request.query_params.get(name, "") for name in LOGIN_FORM_FIELDS}
            try:
                await validate_login_request(provider, params)
            except LoginRequestError as failure:
                return JSONResponse({"error": failure.error, "error_description": failure.description}, status_code=400)
            return HTMLResponse(render_login_form(params))

        form = await request.form()
        params = {name: str(form.get(name, "")) for name in LOGIN_FORM_FIELDS}
        client_ip = _client_ip(request)
        retry_after = _throttler.retry_after(client_ip)
        if retry_after > 0:
            return HTMLResponse(
                render_login_form(params, error=f"Too many attempts; retry in {int(retry_after) + 1}s."),
                status_code=429,
                headers={"Retry-After": str(int(retry_after) + 1)},
            )
        try:
            client, redirect_uri, challenge, scopes, resource = await validate_login_request(provider, params)
        except LoginRequestError as failure:
            return JSONResponse({"error": failure.error, "error_description": failure.description}, status_code=400)
        if not verify_password(str(form.get("password", ""))):
            _throttler.record_failure(client_ip)
            return HTMLResponse(render_login_form(params, error="Invalid credentials."), status_code=401)
        _throttler.record_success(client_ip)
        code = provider.issue_authorization_code(client, redirect_uri, challenge, scopes, resource)
        extras = {"state": params["state"]} if params.get("state") else {}
        return RedirectResponse(construct_redirect_uri(str(redirect_uri), code=code.code, **extras), status_code=302)

    return [Route(LOGIN_PATH, login_endpoint, methods=["GET", "POST"])]


def _build_resource_bound_token_route(provider: YYAuthorizationServerProvider) -> Route:
    """SDK /token endpoint composed with the RFC 8707 resource-equality guard.

    The SDK ``TokenHandler`` owns client authentication, redirect binding, and
    PKCE; the guard only compares the token request's ``resource`` against the
    one bound to the authorization code before the exchange runs.
    """
    from mcp.server.auth.handlers.token import TokenHandler
    from mcp.server.auth.middleware.client_auth import ClientAuthenticator
    from mcp.server.auth.routes import _body_limited, _cors, request_response

    handler = TokenHandler(provider, ClientAuthenticator(provider))

    async def token_endpoint(request: Request) -> Any:
        if request.method == "POST":
            form = await request.form()
            code = form.get("code")
            resource = form.get("resource")
            if isinstance(code, str) and not provider.token_request_resource_matches(
                code, resource if isinstance(resource, str) else None
            ):
                return JSONResponse(
                    {"error": "invalid_grant", "error_description": "resource does not match the authorization request."},
                    status_code=400,
                    headers={"Cache-Control": "no-store"},
                )
        return await handler.handle(request)

    # Mirror create_auth_routes' /token composition exactly, with the guard added.
    endpoint = _cors(_body_limited(request_response(token_endpoint)), ["POST", "OPTIONS"])
    return Route(TOKEN_PATH, endpoint=endpoint, methods=["POST", "OPTIONS"])


# --- Assembly ---
class OAuthAssembly:
    """Everything server.py needs to mount the OAuth boundary."""

    def __init__(
        self,
        *,
        provider: YYAuthorizationServerProvider,
        verifier: JWTVerifier,
        remote_provider: RemoteAuthProvider,
        routes: list[BaseRoute],
        middleware: list[Middleware],
        issuer: str,
        resource: str,
        metadata_url: str,
    ) -> None:
        self.provider = provider
        self.verifier = verifier
        self.remote_provider = remote_provider
        self.routes = routes
        self.middleware = middleware
        self.issuer = issuer
        self.resource = resource
        self.metadata_url = metadata_url


def build_oauth_stack(issuer: str | None = None) -> OAuthAssembly:
    """Assemble the SDK-native OAuth 2.1 stack. Requires ``configure_auth``."""
    if not _auth_secret:
        raise RuntimeError("auth.configure_auth() must run before build_oauth_stack().")
    issuer_url = AnyHttpUrl((_auth_issuer or issuer or "http://127.0.0.1").rstrip("/"))
    issuer_text = str(issuer_url)  # canonical spelling used by metadata and tokens
    signing_key = derive_jwt_key(high_entropy_material=_auth_secret, salt=issuer_text)
    token_issuer = JWTIssuer(issuer=issuer_text, audience=issuer_text, signing_key=signing_key)
    verifier = YYTokenVerifier(signing_key=signing_key, issuer=issuer_text, resource=issuer_text)
    client_manager = CIMDClientManager(
        enable_cimd=True,
        default_scope=PRODUCTION_SCOPE,
        allowed_redirect_uri_patterns=None,  # per-document allowlists (CIMD) / registered URIs (DCR)
    )
    provider = YYAuthorizationServerProvider(
        client_manager=client_manager, token_issuer=token_issuer, verifier=verifier, resource=issuer_text
    )

    remote_provider = RemoteAuthProvider(
        token_verifier=verifier,
        authorization_servers=[issuer_url],
        base_url=issuer_url,
        scopes_supported=[PRODUCTION_SCOPE],
    )

    as_routes = [
        route
        for route in create_auth_routes(
            provider,
            issuer_url,
            client_registration_options=ClientRegistrationOptions(
                enabled=True,
                valid_scopes=list(SUPPORTED_SCOPES),
                default_scopes=[PRODUCTION_SCOPE],
            ),
        )
        if getattr(route, "path", None) != TOKEN_PATH  # replaced below with the resource-bound one
    ]
    routes: list[BaseRoute] = [
        *remote_provider.get_routes(),  # RFC 9728 /.well-known/oauth-protected-resource
        *as_routes,
        _build_resource_bound_token_route(provider),
        *build_login_routes(provider),
    ]
    metadata_url = f"{issuer_text.rstrip('/')}{WELL_KNOWN_PROTECTED_RESOURCE}"
    middleware = [Middleware(BearerChallengeMiddleware, verifier=verifier, resource_metadata_url=metadata_url)]
    return OAuthAssembly(
        provider=provider,
        verifier=verifier,
        remote_provider=remote_provider,
        routes=routes,
        middleware=middleware,
        issuer=issuer_text,
        resource=issuer_text,
        metadata_url=metadata_url,
    )
