export const CLUSTERS = [ 
  { id: 'T1_DATABASE', label: 'database', keywords: ['database', 'sql', 'schema', 'migration', 'data', '\u6570\u636e\u5e93'], candidates: ['be-architect', 'implementation', 'be-validator', 'be-provider', 'sdlc'], phases: [['be-architect'], ['implementation', 'be-provider'], ['be-validator', 'sdlc']], contract: 'database contract', preconditions: ['be-architect 数据库 schema/数据契约产物须先冻结（contracts/<planId>.json 或 --contract），下游 implementation/be-provider 才开工', '每子任务产物须含资产消费锚点 + ≥1 内核词（D-1 机验，缺则 assetConsumed=false）'] }, 
  { id: 'T2_BACKEND', label: 'backend', keywords: ['backend', 'api', 'login', 'server', '\u540e\u7aef', '\u767b\u5f55', '\u63a5\u53e3'], candidates: ['be-architect', 'implementation', 'be-provider', 'be-resilience', 'sdlc', 'security', 'review', 'be-validator'], phases: [['be-architect'], ['implementation', 'be-provider', 'be-resilience', 'security'], ['sdlc', 'review'], ['be-validator']], contract: 'backend interface and error contract', requireExec: true, preconditions: ['be-architect 接口/错误契约产物须先冻结（contracts/<planId>.json 或 --contract OpenAPI），下游才放行', '实现类子任务须经 --exec 宿主真实执行，禁纯 prompt 兜底（requireExec）', '每子任务产物须含资产消费锚点 + ≥1 内核词（D-1）；上游 done 且 assetConsumed=true 后下游才派单'] },
  { id: 'T3_AI_RAG_MCP', label: 'ai-rag-mcp', keywords: ['ai', 'rag', 'mcp', 'agent', 'model', '\u6a21\u578b', '\u77e5\u8bc6\u5e93'], candidates: ['be-provider', 'implementation', 'agent-research', 'be-validator', 'dev-planner'], phases: [['be-provider'], ['implementation', 'agent-research'], ['be-validator', 'dev-planner']], contract: 'model and tool contract', preconditions: ['模型/工具选型契约（be-provider/agent-research 调研结论）须先产出冻结，implementation 后行', '每子任务产物须含资产消费锚点 + ≥1 内核词（D-1 机验）'] }, 
  { id: 'T4_FRONTEND', label: 'frontend', keywords: ['frontend', 'page', 'web', 'responsive', 'component', 'landing', 'ui', 'ux', '\u524d\u7aef', '\u9875\u9762'], candidates: ['frontend-design', 'frontend-visual-validation', 'agent-vision-toolkit', 'colorize', 'planning', 'review', 'security'], phases: [['frontend-design'], ['frontend-visual-validation', 'colorize', 'planning'], ['review', 'security', 'agent-vision-toolkit']], contract: 'frontend interaction contract', preconditions: ['后端接口契约先冻结（FR-3：contractMode:\'frozen\'，缺契约 CONTRACT_NOT_FROZEN skip）', 'Gate A 用户 APPROVED + PARITY_CHECK 冻结 token 先于组件实现', '每子任务产物须含资产消费锚点 + ≥1 内核词（D-1 机验）'] },
  { id: 'T5_OPS', label: 'ops', keywords: ['ops', 'deploy', 'monitor', 'log', 'ci', 'docker', '\u8fd0\u7ef4'], candidates: ['be-resilience', 'security', 'skill-sentinel', 'be-validator', 'review'], phases: [['be-resilience', 'security', 'skill-sentinel'], ['be-validator', 'review']], contract: 'operations contract', preconditions: ['加固/扫描产物（be-resilience/security/skill-sentinel）须先于验收子任务（be-validator/review）', '每子任务产物须含资产消费锚点 + ≥1 内核词（D-1 机验）'] },
]; 
export const PRIORITY = ['T2_BACKEND', 'T4_FRONTEND', 'T1_DATABASE', 'T3_AI_RAG_MCP', 'T5_OPS']; 
export function getCluster(id) { return CLUSTERS.find(function(cluster) { return cluster.id === id; }); }
