import { chromium } from 'playwright-core';
const exe = 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe';
const b = await chromium.launch({ executablePath: exe, headless: true });
const p = await (await b.newContext()).newPage();
const errs = []; p.on('console', m => errs.push(m.type() + ': ' + m.text())); p.on('pageerror', e => errs.push('PAGEERROR: ' + e.message));
await p.goto('http://127.0.0.1:8102/index-mock.html', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(1500);
console.log('GUIDE_CONTENT type:', await p.evaluate(() => typeof GUIDE_CONTENT));
console.log('phases-list children:', await p.evaluate(() => document.getElementById('phases-list').children.length));
console.log('asset-grid children:', await p.evaluate(() => document.getElementById('asset-grid').children.length));
console.log('next-section hidden:', await p.evaluate(() => document.getElementById('next-section').hidden));
console.log('page-meta:', await p.evaluate(() => document.getElementById('page-meta').textContent));
console.log('loading hidden:', await p.evaluate(() => document.getElementById('loading').hidden));
console.log('--- console ---'); console.log(errs.join('\n') || '(none)');
await b.close();
