import { chromium } from 'playwright-core';
const exe = 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe';
const b = await chromium.launch({ executablePath: exe, headless: true });
const p = await (await b.newContext()).newPage();
const errs = []; p.on('console', m => errs.push(m.type() + ': ' + m.text()));
const failed = []; p.on('requestfailed', r => failed.push(r.url()));
p.on('response', r => { if (r.status() >= 400) failed.push(r.status() + ' ' + r.url()); });
await p.goto('http://127.0.0.1:8102/index-mock.html', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(1500);
console.log('next-hint:', JSON.stringify(await p.evaluate(() => document.getElementById('next-hint').textContent)));
console.log('next-section hidden attr:', await p.evaluate(() => document.getElementById('next-section').getAttribute('hidden')));
console.log('next-section isHidden:', await p.locator('#next-section').isHidden());
console.log('failed reqs:', failed);
console.log('console:', errs);
await b.close();
