import { chromium } from 'playwright-core';
const exe = 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe';
const b = await chromium.launch({ executablePath: exe, headless: true });
const ctx = await b.newContext();
const p = await ctx.newPage();
const errs = []; p.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
await p.goto('http://127.0.0.1:8102/index-mock.html', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(1200);
console.log('GUIDE_CONTENT:', await p.evaluate(() => typeof GUIDE_CONTENT));
console.log('phases:', await p.evaluate(() => document.querySelectorAll('.phase-item').length));
console.log('assets:', await p.evaluate(() => document.querySelectorAll('.asset-card').length));
console.log('next hidden:', await p.evaluate(() => document.getElementById('next-section').hidden));
console.log('next-hint:', JSON.stringify(await p.evaluate(() => document.getElementById('next-hint').textContent)));
console.log('copy btn visible:', await p.locator('#copy-next-prompt').isVisible());
console.log('errors:', errs);
await b.close();
